import Head from "next/head";

const SEO = ({
  pageTitle,
  description,
  keywords,
  url,
  image,
  type = "website",
  schema,
}) => {
  const siteName = "Speaksure";
  const siteUrl = "https://speaksure.in"; // change to your domain

  const fullTitle = pageTitle ? `${siteName} - ${pageTitle}` : siteName;

  return (
    <Head>
      {/* Basic SEO */}
      <title>{fullTitle}</title>
      <meta name="description" content={description} />
      <meta name="keywords" content={keywords} />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta httpEquiv="x-ua-compatible" content="ie=edge" />

      {/* Open Graph (Facebook) */}
      <meta property="og:type" content={type} />
      <meta property="og:title" content={fullTitle} />
      <meta property="og:description" content={description} />
      <meta property="og:url" content={url || siteUrl} />
      <meta property="og:image" content={image || `${siteUrl}/og-image.jpg`} />

      {/* Twitter */}
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:title" content={fullTitle} />
      <meta name="twitter:description" content={description} />
      <meta name="twitter:image" content={image || `${siteUrl}/og-image.jpg`} />

      {/* Favicon */}
      <link rel="icon" href="/assets/images/favicon1.png" />

      {/* Structured Data */}
      {schema && (
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
        />
      )}
    </Head>
  );
};

export default SEO;





// old code 27-02-2026

// import Head from "next/head";

// const SEO = ({ pageTitle, font }) => (
//     <Head>
//         <title>
//             {pageTitle && `Speaksure - ${pageTitle} `}
//         </title>
//         <meta httpEquiv="x-ua-compatible" content="ie=edge" />
//         <meta name="description" content="Generated by create next app" />
//           <meta name="keywords" content="spoken english in karur, spoken hindi karur, spoken french karur, spoken german karur, english training karur, speaksure in karur, spoken english, celpip karur, ielts karur, pte karur, toefl karur" />
//           {/*   <meta name="robots" content="noindex, follow" />  */}
//         <meta
//             name="viewport"
//             content="width=device-width, initial-scale=1, shrink-to-fit=no"
//         />
//         {font && <link href={font} rel="stylesheet" />}
//         <link rel="icon" type="image/png" href="/assets/images/favicon1.png"/>
//     </Head>
// )

// export default SEO;
